# This workflow will test this project.
name: Github Action CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    name: Go Test
    strategy:
      matrix:
        go-version: ["1.13", "1.19", "1.20"]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Run Unit Test Cases
      run: go test -v -coverprofile=coverage.out -covermode=count ./...
    - name: Upload Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
